###consulta de instância simplificada
GET http://127.0.0.1:5984/

### consultando a instância do couch db detalhada
GET / HTTP/1.1
Host: 127.0.0.1:5984

### lisar todos os bancos de dados da instância
GET http://music_admin:fib01123@127.0.0.1:5984/_all_dbs

### requisição a um banco específico:
GET http://music_admin:fib01123@127.0.0.1:5984/esquema_vinicola

### requisição a um documento específico:
GET http://music_admin:fib01123@127.0.0.1:5984/esquema_vinicola/_all_docs

### requisição ao conteúdo do doc
GET http://music_admin:fib01123@127.0.0.1:5984/esquema_vinicola/_all_docs?include_docs=true
